name: Build/Push Image and Release Charts

on:
  push:
    branches:
      - dev
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set env
        run: echo "IMAGE_TAG=\"v10.0.0.${{ github.run_number }}-g$(echo $GITHUB_SHA | cut -c 1-6)\"" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          env | sort
